// translator.rs

use crate::lexer::token::TokenType;
use crate::parser;
use crate::{error::TackyError, tacky::tacky};
use parser::c_ast::{
    Expr as AstExpr, Function as AstFunction, LiteralExpr as AstLiteralExpr, Program as AstProgram,
    Stmt as AstStmt,
};
use std::vec::Vec;
use tacky::{
    FunctionDefinition as TackyFunctionDefinition, Instruction as TackyInstruction,
    Program as TackyProgram, UnaryOperator as TackyUnaryOperator, Value as TackyValue,
};

// A helper to manage temporary variable names
struct TempGenerator {
    counter: usize,
}

impl TempGenerator {
    fn new() -> Self {
        TempGenerator { counter: 0 }
    }

    fn next(&mut self) -> String {
        let name = format!("tmp.{}", self.counter);
        self.counter += 1;
        name
    }
}

pub struct AstToTackyTranslator<'a> {
    temp_generator: TempGenerator,
    source: &'a str,
    // Add other state if needed, like a symbol table
}

impl<'a> AstToTackyTranslator<'a> {
    pub fn new(source: &'a str) -> Self {
        AstToTackyTranslator {
            temp_generator: TempGenerator::new(),
            source: source,
        }
    }

    // Main entry point for translation
    // Translates the AST Program to a TACKY Program
    // Note: The TACKY Program only holds ONE function definition.
    // This translator will assume the AST Program has exactly one function
    // or only process the first one.
    pub fn translate_program(
        &mut self,
        ast_program: AstProgram,
    ) -> Result<TackyProgram, TackyError> {
        if ast_program.functions.is_empty() {
            // TACKY Program must have a function definition
            return Err(TackyError {
                message: "AST Program must contain at least one function for this TACKY target."
                    .to_string(),
            });
        }
        if ast_program.functions.len() > 1 {
            eprintln!(
                "Warning: AST Program contains more than one function, only the first will be translated to TACKY."
            );
        }

        let ast_function = ast_program.functions.into_iter().next().unwrap(); // Take the first function

        let tacky_function = self.translate_function(ast_function)?;

        Ok(TackyProgram {
            definition: tacky_function,
        })
    }

    // Translates an AST Function to a TACKY FunctionDefinition
    fn translate_function(
        &mut self,
        ast_function: AstFunction,
    ) -> Result<TackyFunctionDefinition, TackyError> {
        let function_name = ast_function.name.get_lexeme(self.source);
        let mut tacky_body: Vec<TackyInstruction> = Vec::new();

        // Translate each statement in the function body
        for stmt in ast_function.body {
            let instructions = self.translate_stmt(stmt)?;
            tacky_body.extend(instructions); // Add generated instructions to the body
        }

        Ok(TackyFunctionDefinition {
            name: function_name.to_string(),
            body: tacky_body,
        })
    }

    // Translates an AST Statement to a sequence of TACKY Instructions
    fn translate_stmt(&mut self, ast_stmt: AstStmt) -> Result<Vec<TackyInstruction>, TackyError> {
        let mut instructions: Vec<TackyInstruction> = Vec::new();

        match ast_stmt {
            AstStmt::Return { keyword: _, value } => {
                // The provided TACKY ASDL is Return(val), implying a value is always returned.
                // We'll require a value in the AST Return statement for this translation.
                let expr = value.ok_or(TackyError {
                    message: "AST Return statement must have a value for this TACKY target."
                        .to_string(),
                })?;

                // Translate the expression. This will generate instructions to compute the expression
                // and return the TACKY Value representing the result.
                let (expr_instructions, result_value) = self.translate_expr(expr)?;

                // Add the instructions generated by the expression
                instructions.extend(expr_instructions);

                // Add the final Return instruction
                instructions.push(TackyInstruction::Return(result_value));
            } // Handle other statement types if the AST had them (e.g., assignments)
              // _ => return Err(format!("Unsupported AST statement type: {:?}", ast_stmt)),
        }

        Ok(instructions)
    }

    // Translates an AST Expression into a sequence of TACKY Instructions
    // and returns the TACKY Value that holds the expression's result.
    // Complex expressions are broken down using temporary variables.
    fn translate_expr(
        &mut self,
        ast_expr: AstExpr,
    ) -> Result<(Vec<TackyInstruction>, TackyValue), TackyError> {
        let mut instructions: Vec<TackyInstruction> = Vec::new();
        let result_value: TackyValue;

        match ast_expr {
            AstExpr::Literal(AstLiteralExpr::Integer(i)) => {
                // A literal doesn't require any instructions to compute, its value is inherent.
                result_value = TackyValue::Constant(i);
            }
            AstExpr::Unary { operator, right } => {
                // Translate the right-hand side expression first
                let (right_instructions, right_value) = self.translate_expr(*right)?;
                instructions.extend(right_instructions); // Add instructions from the right sub-expression

                // Determine the TACKY unary operator
                let tacky_op = match operator.token_type {
                    TokenType::Minus => TackyUnaryOperator::Negate,
                    TokenType::BitwiseNot => TackyUnaryOperator::Complement,
                    _ => {
                        return Err(TackyError {
                            message: format!(
                                "Unsupported AST unary operator token: {:?}",
                                operator.token_type
                            ),
                        });
                    }
                };

                // The result of the unary operation must be stored in a temporary variable
                let temp_var_name = self.temp_generator.next();
                let dest_value = TackyValue::Var(temp_var_name);

                // Create the TACKY Unary instruction: dest_value = tacky_op right_value
                let unary_instruction = TackyInstruction::Unary {
                    op: tacky_op,
                    src: right_value,
                    dst: dest_value.clone(), // Clone dest_value as it's used in the instruction and as the result
                };
                instructions.push(unary_instruction);

                // The result of this unary expression is the temporary variable
                result_value = dest_value;
            }
            AstExpr::Grouping { expression } => {
                // Grouping is just for parsing precedence, it doesn't create new instructions or change the value.
                // Just translate the inner expression.
                return self.translate_expr(*expression); // Directly return the result of the inner expression
            }
        }

        Ok((instructions, result_value))
    }

    // Helper to map AST Token to Tacky UnaryOperator (already done within translate_expr)
    // fn map_unary_operator(token: &Token) -> Result<TackyUnaryOperator, String> {
    //     match token.token_type {
    //         TokenType::Minus => Ok(TackyUnaryOperator::Negate),
    //         TokenType::Bang => Ok(TackyUnaryOperator::Complement),
    //         _ => Err(format!("Unknown unary operator token type: {:?}", token.token_type)),
    //     }
    // }
}
