// translator.rs

use crate::lexer::token::TokenType;
use crate::parser;
use crate::{error::TackyError, tacky::tacky};
use parser::c_ast::{
    BinaryOperator as AstBinaryOperator, Expr as AstExpr, Function as AstFunction,
    LiteralExpr as AstLiteralExpr, Program as AstProgram, Stmt as AstStmt,
};
use std::vec::Vec;
use tacky::{
    BinaryOperator as TackyBinaryOperator, FunctionDefinition as TackyFunctionDefinition,
    Instruction as TackyInstruction, Program as TackyProgram, UnaryOperator as TackyUnaryOperator,
    Value as TackyValue,
};

// A helper to manage temporary variable names
struct TempGenerator {
    counter: usize,
}

impl TempGenerator {
    fn new() -> Self {
        TempGenerator { counter: 0 }
    }

    fn next(&mut self) -> String {
        let name = format!("tmp.{}", self.counter);
        self.counter += 1;
        name
    }
}
// A helper to manage label  names
struct LabelGenerator {
    counter: usize,
}

impl LabelGenerator {
    fn new() -> Self {
        LabelGenerator { counter: 0 }
    }

    fn next(&mut self) -> String {
        let name = format!("abel.{}", self.counter);
        self.counter += 1;
        name
    }
}
pub struct AstToTackyTranslator<'a> {
    temp_generator: TempGenerator,
    label_generator: LabelGenerator,
    source: &'a str,
    // Add other state if needed, like a symbol table
}

impl<'a> AstToTackyTranslator<'a> {
    pub fn new(source: &'a str) -> Self {
        AstToTackyTranslator {
            temp_generator: TempGenerator::new(),
            label_generator: LabelGenerator::new(),
            source: source,
        }
    }

    // Main entry point for translation
    // Translates the AST Program to a TACKY Program
    // Note: The TACKY Program only holds ONE function definition.
    // This translator will assume the AST Program has exactly one function
    // or only process the first one.
    pub fn translate_program(
        &mut self,
        ast_program: AstProgram,
    ) -> Result<TackyProgram, TackyError> {
        if ast_program.functions.is_empty() {
            // TACKY Program must have a function definition
            return Err(TackyError {
                message: "AST Program must contain at least one function for this TACKY target."
                    .to_string(),
            });
        }
        if ast_program.functions.len() > 1 {
            eprintln!(
                "Warning: AST Program contains more than one function, only the first will be translated to TACKY."
            );
        }

        let ast_function = ast_program.functions.into_iter().next().unwrap(); // Take the first function

        let tacky_function = self.translate_function(ast_function)?;

        Ok(TackyProgram {
            definition: tacky_function,
        })
    }

    // Translates an AST Function to a TACKY FunctionDefinition
    fn translate_function(
        &mut self,
        ast_function: AstFunction,
    ) -> Result<TackyFunctionDefinition, TackyError> {
        let function_name = ast_function.name.get_lexeme(self.source);
        let mut tacky_body: Vec<TackyInstruction> = Vec::new();

        // Translate each statement in the function body
        for stmt in ast_function.body {
            let instructions = self.translate_stmt(stmt)?;
            tacky_body.extend(instructions); // Add generated instructions to the body
        }

        Ok(TackyFunctionDefinition {
            name: function_name.to_string(),
            body: tacky_body,
        })
    }

    // Translates an AST Statement to a sequence of TACKY Instructions
    fn translate_stmt(&mut self, ast_stmt: AstStmt) -> Result<Vec<TackyInstruction>, TackyError> {
        let mut instructions: Vec<TackyInstruction> = Vec::new();

        match ast_stmt {
            AstStmt::Return { keyword: _, value } => {
                // The provided TACKY ASDL is Return(val), implying a value is always returned.
                // We'll require a value in the AST Return statement for this translation.
                let expr = value.ok_or(TackyError {
                    message: "AST Return statement must have a value for this TACKY target."
                        .to_string(),
                })?;

                // Translate the expression. This will generate instructions to compute the expression
                // and return the TACKY Value representing the result.
                let (expr_instructions, result_value) = self.translate_expr(expr)?;

                // Add the instructions generated by the expression
                instructions.extend(expr_instructions);

                // Add the final Return instruction
                instructions.push(TackyInstruction::Return(result_value));
            } // Handle other statement types if the AST had them (e.g., assignments)
              // _ => return Err(format!("Unsupported AST statement type: {:?}", ast_stmt)),
        }

        Ok(instructions)
    }

    // Translates an AST Expression into a sequence of TACKY Instructions
    // and returns the TACKY Value that holds the expression's result.
    // Complex expressions are broken down using temporary variables.
    fn translate_expr(
        &mut self,
        ast_expr: AstExpr,
    ) -> Result<(Vec<TackyInstruction>, TackyValue), TackyError> {
        let mut instructions: Vec<TackyInstruction> = Vec::new();
        let result_value: TackyValue;

        match ast_expr {
            AstExpr::Literal(AstLiteralExpr::Integer(i)) => {
                result_value = TackyValue::Constant(i);
            }
            AstExpr::Unary { operator, right } => {
                // Translate the right-hand side expression first
                let (right_instructions, right_value) = self.translate_expr(*right)?;
                instructions.extend(right_instructions); // Add instructions from the right sub-expression

                // Determine the TACKY unary operator
                let tacky_op = match operator.token_type {
                    TokenType::Minus => TackyUnaryOperator::Negate,
                    TokenType::BitwiseNot => TackyUnaryOperator::Complement, // Assuming ~ maps to Complement
                    TokenType::Bang => TackyUnaryOperator::Bang, // Assuming ! maps to Bang (logical NOT)
                    _ => {
                        return Err(TackyError {
                            message: format!(
                                "Unsupported AST unary operator token: {:?}",
                                operator.token_type
                            ),
                        });
                    }
                };

                // The result of the unary operation must be stored in a temporary variable
                let temp_var_name = self.temp_generator.next();
                let dest_value = TackyValue::Var(temp_var_name);

                // Create the TACKY Unary instruction: dest_value = tacky_op right_value
                let unary_instruction = TackyInstruction::Unary {
                    op: tacky_op,
                    src: right_value,
                    dst: dest_value.clone(), // Clone dest_value as it's used in the instruction and as the result
                };
                instructions.push(unary_instruction);

                // The result of this unary expression is the temporary variable
                result_value = dest_value;
            }
            AstExpr::Grouping { expression } => {
                // Grouping is just for parsing precedence, it doesn't create new instructions or change the value.
                // Just translate the inner expression.
                return self.translate_expr(*expression); // Directly return the result of the inner expression
            }
            AstExpr::Binary {
                operator,
                left,
                right,
            } => {
                // We need a temporary variable to store the final result of the binary operation.
                // This variable will be assigned in different branches (e.g., true/false for boolean ops)
                // or hold the direct result of arithmetic/comparison ops.
                let result_var_name = self.temp_generator.next();
                let result_temp_value = TackyValue::Var(result_var_name); // This will be the returned TackyValue

                if operator == AstBinaryOperator::And {
                    // Translate left side
                    let (left_instructions, left_value) = self.translate_expr(*left)?;
                    instructions.extend(left_instructions);

                    // --- Short-circuiting for AND (A && B) ---
                    // If left is 0 (false), jump directly to the end and set result to 0.
                    // Otherwise, continue to evaluate the right side.
                    let false_label_name = self.label_generator.next();
                    let end_label_name = self.label_generator.next();

                    // If left_value is 0, jump to the false case label
                    instructions.push(TackyInstruction::JumpIfZero {
                        condition: left_value,
                        target: false_label_name.clone(),
                    });

                    // Translate right side (only executed if left_value is non-zero)
                    let (right_instructions, right_value) = self.translate_expr(*right)?;
                    instructions.extend(right_instructions);

                    // If right_value is 0, jump to the false case label
                    instructions.push(TackyInstruction::JumpIfZero {
                        condition: right_value,
                        target: false_label_name.clone(),
                    });

                    // If we reach here, both left and right were non-zero (true).
                    // Set the result variable to 1.
                    instructions.push(TackyInstruction::Copy {
                        src: TackyValue::Constant(1),
                        dst: result_temp_value.clone(),
                    });

                    // Jump to the end label to skip the false case assignment.
                    instructions.push(TackyInstruction::Jump {
                        target: end_label_name.clone(),
                    });

                    // --- False Case Label ---
                    // This is where execution jumps if either left or right was 0.
                    instructions.push(TackyInstruction::Label {
                        name: false_label_name,
                    });

                    // Set the result variable to 0.
                    instructions.push(TackyInstruction::Copy {
                        src: TackyValue::Constant(0),
                        dst: result_temp_value.clone(),
                    });

                    // --- End Label ---
                    // This is the merge point after the boolean logic.
                    instructions.push(TackyInstruction::Label {
                        name: end_label_name,
                    });

                    // The result of the AND expression is stored in result_temp_value.
                    result_value = result_temp_value;
                } else if operator == AstBinaryOperator::Or {
                    // Translate left side
                    let (left_instructions, left_value) = self.translate_expr(*left)?;
                    instructions.extend(left_instructions);

                    // --- Short-circuiting for OR (A || B) ---
                    // If left is non-zero (true), jump directly to the end and set result to 1.
                    // Otherwise, continue to evaluate the right side.
                    let true_label_name = self.label_generator.next();
                    let end_label_name = self.label_generator.next();

                    // If left_value is non-zero, jump to the true case label
                    instructions.push(TackyInstruction::JumpIfNotZero {
                        condition: left_value,
                        target: true_label_name.clone(),
                    });

                    // Translate right side (only executed if left_value is 0)
                    let (right_instructions, right_value) = self.translate_expr(*right)?;
                    instructions.extend(right_instructions);

                    // If right_value is non-zero, jump to the true case label
                    instructions.push(TackyInstruction::JumpIfNotZero {
                        condition: right_value,
                        target: true_label_name.clone(),
                    });

                    // If we reach here, both left and right were 0 (false).
                    // Set the result variable to 0.
                    instructions.push(TackyInstruction::Copy {
                        src: TackyValue::Constant(0),
                        dst: result_temp_value.clone(),
                    });

                    // Jump to the end label to skip the true case assignment.
                    instructions.push(TackyInstruction::Jump {
                        target: end_label_name.clone(),
                    });

                    // --- True Case Label ---
                    // This is where execution jumps if either left or right was non-zero.
                    instructions.push(TackyInstruction::Label {
                        name: true_label_name,
                    });

                    // Set the result variable to 1.
                    instructions.push(TackyInstruction::Copy {
                        src: TackyValue::Constant(1),
                        dst: result_temp_value.clone(),
                    });

                    // --- End Label ---
                    // This is the merge point after the boolean logic.
                    instructions.push(TackyInstruction::Label {
                        name: end_label_name,
                    });

                    // The result of the OR expression is stored in result_temp_value.
                    result_value = result_temp_value;
                } else {
                    // Handle other binary operators (arithmetic, comparison)

                    // Translate both sides first
                    let (left_instructions, left_value) = self.translate_expr(*left)?;
                    let (right_instructions, right_value) = self.translate_expr(*right)?;
                    instructions.extend(left_instructions);
                    instructions.extend(right_instructions);

                    // Determine the TACKY binary operator
                    let tacky_op = match operator {
                        AstBinaryOperator::Add => TackyBinaryOperator::Add,
                        AstBinaryOperator::Multiply => TackyBinaryOperator::Multiply,
                        AstBinaryOperator::Divide => TackyBinaryOperator::Divide,
                        AstBinaryOperator::Subtract => TackyBinaryOperator::Subtract,
                        AstBinaryOperator::Remainder => TackyBinaryOperator::Remainder,
                        AstBinaryOperator::EqualEqual => TackyBinaryOperator::EqualEqual,
                        AstBinaryOperator::Less => TackyBinaryOperator::Less,
                        AstBinaryOperator::LessEqual => TackyBinaryOperator::LessEqual,
                        AstBinaryOperator::Greater => TackyBinaryOperator::Greater,
                        AstBinaryOperator::GreaterEqual => TackyBinaryOperator::GreaterEqual,
                        AstBinaryOperator::BangEqual => TackyBinaryOperator::BangEqual,
                        // Logical AND/OR are handled above
                        AstBinaryOperator::And | AstBinaryOperator::Or => {
                            // This should not be reached because And/Or are handled above,
                            // but good to have a fallback or error here.
                            return Err(TackyError {
                                message: format!(
                                    "Logical AND/OR should have been handled by short-circuit logic, but fell through here: {:?}",
                                    operator
                                ),
                            });
                        }
                    };

                    // Generate the TACKY Binary instruction: result_temp_value = src1 op src2
                    let binary_instruction = TackyInstruction::Binary {
                        op: tacky_op,
                        src1: left_value,
                        src2: right_value,
                        dst: result_temp_value.clone(), // Store result in our temp variable
                    };
                    instructions.push(binary_instruction);

                    // The result of this expression is the temporary variable
                    result_value = result_temp_value;
                }
            }
        }
        Ok((instructions, result_value))
    }
    // Helper to map AST Token to Tacky UnaryOperator (already done within translate_expr)
    // fn map_unary_operator(token: &Token) -> Result<TackyUnaryOperator, String> {
    //     match token.token_type {
    //         TokenType::Minus => Ok(TackyUnaryOperator::Negate),
    //         TokenType::Bang => Ok(TackyUnaryOperator::Complement),
    //         _ => Err(format!("Unknown unary operator token type: {:?}", token.token_type)),
    //     }
    // }
}
